# srs/employee_model.py
# Model for Employee records

#############################################################################
# DO NOT EDIT THIS FILE
# This Code will be replaced by the code generator
#############################################################################

from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
    
from datetime import datetime
from company_model import Company

class Employee(models.Model):
    name        = models.CharField (default='name',max_length=40)
    employeeID  = models.CharField (max_length=40)
    photo       = models.CharField (default='blank.jpg',max_length=200)
    thumbnail   = models.CharField (default='blank-tn.jpg',max_length=200)

    user        = models.ForeignKey (User)
    company     = models.ForeignKey (Company)

    # Format a record as a string
    def __unicode__(self):
        return self.name

    # Back trace a url to a view
    def get_absolute_url(self):
        return reverse('employee-detail', kwargs={'pk': self.pk})

    # Object field handling
    def __iter__(self):
        for i in self.fields():
            yield (i, getattr(self, i))

    # Enumerate the fields
    def fields(self):
        return [ f.name for f in self._meta.fields ]

    # List of values
    def values(self):
        return [ v for f,v in self ]

    # Table of field labels and values
    def table(self):
        return zip(self.fields(),self.values())
